version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    dockerfile: "alpine.Dockerfile"
    target-branch: "main"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"

  - package-ecosystem: "docker"
    directory: "/"
    dockerfile: "debian.Dockerfile"
    target-branch: "main"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"

automerged_updates:
  security-updates: true
  version-requirement: "increase"
  allowed:
    - dependency-type: "direct"
    - dependency-type: "indirect"
  update-types:
    - "version-update:semver-patch"
    - "version-update:semver-minor"
