#!/bin/sh
set -e

# Fix ulimit
ulimit -s unlimited

# Replace Domain
if [ -n "${SITE_URL}" ]; then
  sed -i "s|/localhost|${SITE_URL}|g" /etc/httpd/httpd-vhosts.conf
fi

# Detect Symfony and change DocRoot
if [ -n "${APP_SECRET}" ]; then
  sed -i "s|/var/www/htdocs|/var/www/htdocs/public|g" /etc/httpd/httpd-vhosts.conf
fi

# Apache gets grumpy about PID files pre-existing
if [ -f /tmp/httpd.pid ]; then
  rm -f /tmp/httpd.pid
fi

# Start Apache in the foreground
exec apachectl -D FOREGROUND "$@"