apiVersion: v1
kind: Pod
metadata:
  name: ols
  namespace: exchizo
spec:
  containers:
    - name: ols
      image: litespeedtech/openlitespeed:1.8.2-lsphp83
      imagePullPolicy: Always
      #command: ["sh", "-c", "while true; do echo Hello from Alpine!; sleep 5; done"]