apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: exchizo
spec:
  containers:
    - name: httpd
      image: benhakim2010/php-apache:1.0
      imagePullPolicy: Always
      command: ["sh", "-c", "while true; do echo Hello from Alpine!; sleep 5; done"]