#!/usr/bin/env bash

./configure \
    "--user=webserver" \
    "--group=webserver" \
    "--prefix=/var/www" \
    "--sbin-path=/usr/sbin" \
    "--conf-path=/etc/nginx/nginx.conf" \
    "--pid-path=/var/run/nginx.pid" \
    "--http-log-path=/var/log/nginx/access_log" \
    "--error-log-path=/var/log/nginx/error_log" \
    "--conf-path=/etc/nginx/nginx.conf" \
    "--with-http_ssl_module" \
    "--with-http_realip_module" \
    "--with-http_stub_status_module" \
    "--with-http_gzip_static_module" \
    "--with-http_v2_module" \
    "--with-http_v3_module" \
    "--with-cc-opt='-D FD_SETSIZE=32768'" \
    "--without-select_module" \
    "--without-poll_module" \
    "--without-http_ssi_module" \
    "--without-http_userid_module" \
    "--without-http_autoindex_module" \
    "--without-http_geo_module" \
    "--without-http_map_module" \
    "--without-http_split_clients_module" \
    "--without-http_referer_module" \
    "--without-http_proxy_module" \
    "--without-http_uwsgi_module" \
    "--without-http_scgi_module" \
    "--without-http_memcached_module" \
    "--without-http_empty_gif_module" \
    "--without-http_browser_module" \
    "--without-mail_pop3_module" \
    "--without-mail_imap_module" \
    "--without-mail_smtp_module" \
    "--without-stream_geo_module" \
    "--without-stream_map_module" \
    "--without-stream_return_module" \
    "--without-http_ssi_module"
